### PR TITLE
Various improvements for current version

### PR DESCRIPTION
**Pull request by fabn**
I started to work on a PR for #35, however working in TDD way I found out that current test configuration is completely broken.

As you can see in [any build log](https://travis-ci.org/whomwah/rqrcode/jobs/97617442) current rake default task only executes 6 tests.

I'm not very expert with minitest/unit/test because I mainly use RSpec for my projects however this PR should fix test execution.

There is also a problem in current released version because [present?](https://github.com/whomwah/rqrcode/blob/0dd5d828d4f4e687c4eff7efd9f001bde30191ba/lib/rqrcode/qrcode/qr_numeric.rb#L36) method is used, however that method is only implemented in activesupport. I removed that call and tests are green now.

What do you think of this PR? In my opinion there's some other work to do e.g.
  
* Add a coverage library like simplecov and/or coverall.io
* Uniform tests
  
I can try to address those issues as well but I want to hear from you before doing that.
  
Let me know.

### CODE REVIEW

**Comment by fabn** [comment]
I pushed some other commits, let me know if you want me to split them in different PRs or if you want them rebased/squashed, etc.

Here's a quick recap of what I did

* Fixed test, they weren't running in current codebase.
* Fixed an issue with `#present?` method that's only available in ActiveSupport environments
* Fixed a wrong attr_reader for `error_correction_level`
* Completed all tables for levels 1-40 in all modes, see #35 
* Improved autodetection, if mode is not given choose the best suited mode for the given string.

**Comment by bjornblomqvist** [comment]
Except for that one test that does not actually use alpha numeric it looks really great!!!

**Comment by bjornblomqvist** [comment]
On doing more..

- Uniform tests
  
I think that would be very good.

- Add a coverage library like simplecov and/or coverall.io

I don't see the point of getting coverage statistics. It wont really matter unless someone wants to add tests for the missing coverage. I would much rather see/spend time on new features or better documentation than more tests.

Given the amount of bug reports coming i don't think lack of tests is a problem.

**Comment by fabn** [comment]
> Except for that one test that does not actually use alpha numeric it looks really great!!!

I missed that, now is fixed.

> On doing more..
> 
> Uniform tests
> I think that would be very good.

Which style do you prefer? [Plain minitest/testunit](https://github.com/whomwah/rqrcode/blob/master/test/test_rqrcode.rb#L15) or [minitest/spec](https://github.com/whomwah/rqrcode/blob/master/test/test_rqrcode_export.rb#L19)

> 
> Add a coverage library like simplecov and/or coverall.io
> I don't see the point of getting coverage statistics. It wont really matter unless someone wants to add tests for the missing coverage. I would much rather see/spend time on new features or better documentation than more tests.

I'd do that because it's a low hanging fruit just a [couple of lines required](https://coveralls.zendesk.com/hc/en-us/articles/201769485-Ruby-Rails) and it would have been very useful to detect the wrong configuration before my PR.

It's also useful to detect untested code when new features or any bug fix is developed.

But that's your choice.

**Pull request merged**
