### PR TITLE
Add as_svg_renderer method

### PR DESCRIPTION
**Pull request by akihikodaki**

### CODE REVIEW

**Comment by bjornblomqvist** [comment]
Could you explain the use case? I have not used Content-Security-Policy so its not clear to me what this is for. And how you would use it.

**Comment by akihikodaki** [comment]
@bjornblomqvist Sure. Append `CSPResult.csp` to your `style-src` in `Content-Security-Policy` field in HTTP header. The styles of QR code would be allowed to be shown; other styles not added to `style-src` would be ignored and reported to prevent attacks kind of XSS.

**Comment by bjornblomqvist** [comment]
So if i understand you right you would return the svg with Content-Security-Policy set.

`Content-Security-Policy: style-src 'sha256-hXLriEz22xKNlZLBZHXTURsF5XZHj1Bkjo1s7SNTzSI='`

So this stops other styling on the page from affecting the QRcode?

**Comment by akihikodaki** [comment]
@bjornblomqvist Yes, or you need to add other sources to `style-src` to apply other styles.

**Comment by bjornblomqvist** [comment]
1) I don't think its the job of rqrcode to sha256 of the styles.  I think it would be better to just change so it easy to get the actual style that is used. Basically create a new method that returns the styles and any user interested can use that to generate the sha256 for Content-Security-Policy. We could still keep an example of how to calculate the hash.

2) Have you verified that the hash works in a browser? 

3) Are you/will you use this in production.

**Comment by akihikodaki** [comment]
1\. That makes sense. I will make a change reflecting your opinion.

2 and 3. Yes, here is a commit which is actually running on my server:
https://github.com/kagucho/mastodon/commit/0bbf552a7ec7fc610c621ea49fba61a155cde2c1#diff-0f4625c18c8e5f3e238f36a9af7182edR40

**Comment by bjornblomqvist** [comment]
Looks good! I will merge and release this later this week.

Best Regards Björn Blomqvist

**Comment by akihikodaki** [comment]
Wait, if `style` is used only for `fill`, could we have SVG `fill` property? It should be more straightforward and does not need any Content Security Policy exception. I will close this pull request.

**Pull request closed without merging**
