### PR TITLE
<svg> attributes for id and class

### PR DESCRIPTION
**Pull request by mjy**
Includes https://github.com/whomwah/rqrcode/pull/98.  

* Adds `svg_attributes: {id: '123', class: 'my_qrcode'}` as an option for svg export.  
* Adds specs
* Updates README.md to document options

### CODE REVIEW

**Comment by whomwah** [comment]
Hi, sorry it's taken a long time but I've finally had a change to look it over. I'm happy to merge with a couple of tiny changes.

Firstly this PR seems to be branched from another PR which is branched from another PR all of which are failing the build with conflicts. I wonder if you just fix your PR so we get a green build?

The small change is to update the way the `svg` is constructed so that the existing `spec/rqrcode/data.rb` does not change. This would prove the changes are backward compatible and opt-in. So:

```
open_tag = %(<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ev="http://www.w3.org/2001/xml-events")

...
open_tag += %( shape-rendering="#{shape_rendering}">)
...
```

**Comment by mjy** [comment]
>  I wonder if you just fix your PR so we get a green build?

Not quite sure, but maybe you mean that I should fork HEAD, diff that with my branch, and create a single commit branch to PR on?

**Comment by whomwah** [comment]
I know your works builds on (and makes a previous MR opt-in too) and they all look good, I'm just thinking of the best way to get this into a state where it can be merged cleanly.

**Comment by whomwah** [comment]
There's not much movement on this but I see these changes as useful and opt in. I will create a new PR and reference the various parties involved in the commit message.

**Pull request closed without merging**
